# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  increment_version_number(version_number: "1.0.0")
  increment_build_number(build_number: 2202251)

  lane :adhoc do
    build_app(
      workspace: "web.xcworkspace",
      scheme: "web",
      configuration: "Release",
      silent: true,
      destination: "generic/platform=iOS",
      export_options: {iCloudContainerEnvironment: 'Production'},
      include_bitcode: true,
      export_method: "ad-hoc",
      output_directory: '/Users/panxue/Downloads/archives',
    )
  end
end
